------------------------------------------------------------------------------------------------------------------
# PPGMC - FURG | 03043P - Algoritmos e Programas | 02/2023

Este notebook contém a resolução da tarefa referente ao tópico 11 da disciplina 03043P - Algoritmos e Programas do Programa de Pós-Graduação em Modelagem Computacional da FURG (PPGMC-FURG).
* **Docente:** Dr. Leonardo Ramos Emmendorfer.
* **Discente:** Vitor Avelaneda.
    * **Contato:** avelaneda.vitor@gmail.com

O repositório com os notebooks pode ser acessado [aqui](https://github.com/vitoravelaneda/03043P-Algoritmos_e_Programas-PPGMC-FURG), e este notebook pode ser acessado [aqui!](https://github.com/vitoravelaneda/03043P-Algoritmos_e_Programas-PPGMC-FURG/blob/main/notebooks/tarefa_topico_11.ipynb)

------------------------------------------------------------------------------------------------------------------

# Tarefa Tópico 11

Executar todos os códigos em Python mostrados no [vídeo](https://youtu.be/Blzp9iuhZqo?si=RnC-XoKhcPi-Odz7). Entregar arquivo texto contendo os códigos.


In [1]:
from numpy import *

arr1 = array([[1,2,3],
              [4,5,6]]) # Este trecho cria uma matriz bidimensional usando 'array' do NumPy.

print(f'ndim retorna a dimensionalidade da matriz: {arr1.ndim}')
print(f'shape retorna a forma da matriz: {arr1.shape}')
print(f'size retorna o número total de elementos na matriz: {arr1.size}')

arr2 = arr1.flatten() 
print(f'flatten() transforma a matriz em uma única dimensão: {arr2}') 

ndim retorna a dimensionalidade da matriz: 2
shape retorna a forma da matriz: (2, 3)
size retorna o número total de elementos na matriz: 6
flatten() transforma a matriz em uma única dimensão: [1 2 3 4 5 6]


In [2]:
arr1 = array([[1,2,3,6,2,9], 
              [4,5,6,7,5,3]])

# Usando flatten para transformar a matriz em uma dimensão.
arr2 = arr1.flatten()

# Usando reshape para reorganizar a matriz para uma forma específica.
arr3 = arr1.reshape(3,4) # reorganizar a matriz com 3 linhas e 4 colunas.

# Imprimindo a matriz resultante após a operação reshape.
print(arr3)

[[1 2 3 6]
 [2 9 4 5]
 [6 7 5 3]]


In [3]:
arr1 = array([[1,2,3,6,2,9], 
              [4,5,6,7,5,3]])

# Usando flatten para transformar a matriz em uma dimensão.
arr2 = arr1.flatten()

# Usando reshape para reorganizar a matriz para uma forma específica.
arr3 = arr1.reshape(2,2,3) # reorganizar a matriz com 2 blocos, 2 linhas e 3 colunas.

# Imprimindo a matriz resultante após a operação reshape.
print(arr3)

[[[1 2 3]
  [6 2 9]]

 [[4 5 6]
  [7 5 3]]]


In [4]:
m = matrix('1 2 3; 6 4 5;1 6 7') # Cria uma matriz 3x3 chamada m usando a função matrix do NumPy.
print(diagonal(m)) # obtem a diagonal principal da matriz 'm' e imprime.
print(m.min()) # obtem o valor mínimo da matriz 'm' e imprime.
print(m.max()) # obtem o valor máximo da matriz 'm' e imprime.

[1 4 7]
1
7


In [5]:
m1 = matrix('1 2 3; 6 4 5; 1 6 7')
m2 = matrix('1 2 3; 6 8 5; 2 6 7')

m3 = m1 + m2;
print(m3)

[[ 2  4  6]
 [12 12 10]
 [ 3 12 14]]


In [6]:
m1 = matrix('1 2 3; 6 4 5; 1 6 7')
m2 = matrix('1 2 3; 6 8 5; 2 6 7')

m3 = m1 - m2;
print(m3)

[[ 0  0  0]
 [ 0 -4  0]
 [-1  0  0]]


In [7]:
m1 = matrix('1 2 3; 6 4 5; 1 6 7')
m2 = matrix('1 2 3; 6 8 5; 2 6 7')

m3 = m1 * m2;
print(m3)

[[19 36 34]
 [40 74 73]
 [51 92 82]]


------------------------------------------------------------------------------------------------------------------