------------------------------------------------------------------------------------------------------------------
# PPGMC - FURG | 03043P - Algoritmos e Programas | 02/2023

Este notebook contém a resolução da tarefa referente ao tópico 12 da disciplina 03043P - Algoritmos e Programas do Programa de Pós-Graduação em Modelagem Computacional da FURG (PPGMC-FURG).
* **Docente:** Dr. Leonardo Ramos Emmendorfer.
* **Discente:** Vitor Avelaneda.
    * **Contato:** avelaneda.vitor@gmail.com

O repositório com os notebooks pode ser acessado [aqui](https://github.com/vitoravelaneda/03043P-Algoritmos_e_Programas-PPGMC-FURG), e este notebook pode ser acessado [aqui!](https://github.com/vitoravelaneda/03043P-Algoritmos_e_Programas-PPGMC-FURG/blob/main/notebooks/tarefa_topico_12.ipynb)

------------------------------------------------------------------------------------------------------------------

# Tarefa Tópico 12

1) Ler o arquivo em http://techtldr.com/wp-content/uploads/actors.csv por meio de código em Python, usando o pacote "csv".


In [1]:
import csv
from urllib.request import urlopen

url_atores = 'http://techtldr.com/wp-content/uploads/actors.csv'

resposta = urlopen(url_atores)

df = csv.reader(resposta.read().decode('utf-8').splitlines())

for row in df:
    print(row)

['First Name', 'Last Name', 'Date of Birth']
['Tom', 'Cruise', 'July 3, 1962']
['Bruce', 'Willis', 'March 19, 1955']
['Morgan', 'Freeman', 'June 1, 1937']
['John', 'Wayne', 'May 26, 1907']


2) Retirar o cabeçalho do arquivo lido.

In [2]:
import csv
from urllib.request import urlopen

url_atores = 'http://techtldr.com/wp-content/uploads/actors.csv'

resposta = urlopen(url_atores)
df = csv.reader(resposta.read().decode('utf-8').splitlines())

# Ignorar a primeira linha (cabeçalho)
next(df, None)

# Iterar sobre as linhas restantes
for row in df:
    print(row)

['Tom', 'Cruise', 'July 3, 1962']
['Bruce', 'Willis', 'March 19, 1955']
['Morgan', 'Freeman', 'June 1, 1937']
['John', 'Wayne', 'May 26, 1907']


3) Calcular automaticamente a média entre todas as idades dos artistas descritos no arquivo.

In [3]:
import csv
from urllib.request import urlopen
from datetime import datetime

url_atores = 'http://techtldr.com/wp-content/uploads/actors.csv'

resposta = urlopen(url_atores)
df = csv.reader(resposta.read().decode('utf-8').splitlines())

# Ignorar a primeira linha (cabeçalho)
next(df, None)

# Lista para armazenar as idades
idades = []

# Obtém as idades e adiciona à lista
for row in df:
    data_do_aniversario = datetime.strptime(row[2], '%B %d, %Y')
    idade = datetime.now().year - data_do_aniversario.year
    idades.append(idade)

# Calcular a média das idades
idade_media = sum(idades) / len(idades)

print(f'Média de idades dos artistas: {idade_media:.2f} anos')


Média de idades dos artistas: 82.75 anos


4) Salvar localmente o seguinte arquivo:  https://raw.githubusercontent.com/emmendorfer/idwr/main/demo/datasets/amazon.csv

In [4]:
import pandas as pd

url_amazon = "https://raw.githubusercontent.com/emmendorfer/idwr/main/demo/datasets/amazon.csv"
local_filename = "amazon.csv"

# Faz o download do arquivo CSV e lê diretamente para um DataFrame do pandas
df = pd.read_csv(url_amazon)

# Salva o DataFrame em um arquivo CSV local
df.to_csv(local_filename, index=False, encoding='utf-8')

print(f'O arquivo foi salvo localmente como {local_filename}')



O arquivo foi salvo localmente como amazon.csv


5) Converter os dados lidos para uma matriz do "numpy" usando "pandas".  Utilizar as funções read_csv() e to_numpy() 

In [5]:
import pandas as pd

# Ler o arquivo CSV usando pandas
amazon_df = pd.read_csv("amazon.csv", header=None)

# Converter os dados para uma matriz do numpy usando to_numpy()
amazon_matriz = amazon_df.to_numpy()

# Imprimir a matriz
print(amazon_matriz)


[[9.8700e-01 6.2924e+01 5.0060e+02]
 [4.0970e+00 6.3145e+01 2.7481e+03]
 [6.6500e+00 6.9869e+01 1.0186e+03]
 [3.2950e+00 6.0628e+01 2.0876e+03]
 [3.1040e+00 6.0016e+01 2.7511e+03]
 [5.7890e+00 6.1288e+01 2.6105e+03]
 [2.0570e+00 6.0026e+01 5.0420e+02]
 [1.2500e-01 6.7061e+01 8.9900e+01]]


6) Obtenha um arquivo CSV com dados relacionados aos seus interesses acadêmicos. Faça a leitura do arquivo em Python. 

In [6]:
import pandas as pd
from urllib.request import urlopen

url_molecula = "https://raw.githubusercontent.com/vitoravelaneda/plot_moleculas/main/input/h2o_neutral.csv"

df = pd.read_csv(url_molecula, encoding='utf-8')

print(df) # df.head(), df.tail(), df.sample() também é opção.

     wavel($\mu$m)  intensity(km/kmol)
0         0.000000                 0.0
1         0.516864                 0.0
2         0.930354                 0.0
3         1.261147                 0.0
4         1.525781                 0.0
..             ...                 ...
245      18.658124                 0.0
246      21.188405                 0.0
247      24.224743                 0.0
248      27.868349                 0.0
249      32.240676                 0.0

[250 rows x 2 columns]


------------------------------------------------------------------------------------------------------------------